version: "3"
services:
  inventory:
    image: coffee-shop/inventory
    ports:
      - 9090:9090
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  coffee-shop-bff:
    image: coffee-shop/coffee-shop-bff
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
    depends_on:
      - inventory
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  coffee-shop-ui:
    image: coffee-shop/coffee-shop-ui
    ports:
      - 8080:80
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  frontend:
  backend:

volumes:
  coffee-images:
